runtime: python312
env: flex

service_account: django-app-service@faccialattendancev2.iam.gserviceaccount.com

service: default
# Remove the 'bucket' line here
entrypoint: gunicorn -b :8080 --workers 2 --timeout 120 core.wsgi:application



env_variables:
  DJANGO_SETTINGS_MODULE: "core.settings"
  SECRET_KEY: "django-insecure-8et)q^w)w25bn%$7lik+$nwi!n7p82*n*fy3--txqv8gr!lfg-"
  DB_NAME: "Student_data"
  DB_USER: "students"
  DB_PASSWORD: "Danish121@."
  DB_HOST: "/cloudsql/facialattendance-458317:us-central1:facial-attendance-db"
  GS_BUCKET_NAME: "facial-media-faccialattendancev2"  # For media files

beta_settings:
  cloud_sql_instances: "faccialattendancev2:us-central1:facial-attendance-db"

manual_scaling:
  instances: 1