# Generated by Django 5.1.7 on 2025-03-17 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="students",
            name="roll_no",
            field=models.IntegerField(unique=True),
        ),
    ]
