# Generated by Django 5.1.7 on 2025-03-17 20:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_alter_students_roll_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="time",
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="status",
            field=models.CharField(
                choices=[("Present", "Present"), ("Absent", "Absent")],
                default="Absent",
                max_length=10,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together={("student", "date")},
        ),
    ]
