# Generated by Django 5.1.7 on 2025-05-01 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_attendance_time_alter_attendance_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="status",
            field=models.CharField(
                choices=[("Present", "Present"), ("Absent", "Absent")],
                default="Present",
                max_length=10,
            ),
        ),
    ]
