# Generated by Django 5.1.7 on 2025-05-01 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_alter_attendance_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="students",
            name="roll_no",
            field=models.BigIntegerField(unique=True),
        ),
    ]
